package com.example.permissiontest

const val sampleJson = """{
    "list": [
        {
            "id": 15964128,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"코박라이브 겨우겨우 참여했네..\"",
            "timestamp": "1679911543",
            "post_id": 879590,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15957715,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"슈퍼 인플루언서들이 홍보한 ..\"",
            "timestamp": "1679758366",
            "post_id": 878861,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15957048,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"너무나도 보고 싶었던 사진\"",
            "timestamp": "1679717029",
            "post_id": 878760,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15955990,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"권도형, 국내 대형 로펌에 ..\"",
            "timestamp": "1679658985",
            "post_id": 878288,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15951067,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"BTC 백만 달러 간다. 두..\"",
            "timestamp": "1679614180",
            "post_id": 877744,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15950056,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"텔레그램, 테더 전송 지원 ..\"",
            "timestamp": "1679577203",
            "post_id": 877373,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15940465,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"일본 후지쯔 암호화폐 및 금..\"",
            "timestamp": "1679442808",
            "post_id": 875409,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15939077,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"엥? 리플이 10% 넘게 반..\"",
            "timestamp": "1679405518",
            "post_id": 874929,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15928928,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"비트코인 2만 8천 달러 회..\"",
            "timestamp": "1679324169",
            "post_id": 873965,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15927484,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"8시 코박라이브 당첨이요~\"",
            "timestamp": "1679310121",
            "post_id": 873724,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15922532,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"국내 가상자산 사업자, 영업..\"",
            "timestamp": "1679219104",
            "post_id": 872916,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15921375,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"버핏, 은행 위기에 등판. ..\"",
            "timestamp": "1679191407",
            "post_id": 872824,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15920036,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"#종가 맞추기. 또 침펜치 ..\"",
            "timestamp": "1679143173",
            "post_id": 872673,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15918603,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"뱅크런 이후의 승자는 비트와..\"",
            "timestamp": "1679099892",
            "post_id": 872536,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15912398,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"말 많은 근로시간 개편안. ..\"",
            "timestamp": "1679009400",
            "post_id": 871558,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15911031,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"역외 위안화 스테이블 코인이..\"",
            "timestamp": "1678962881",
            "post_id": 870884,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15910539,
            "type": "ADMIN_REWARD",
            "text": "뿌립니다",
            "timestamp": "1678958946",
            "post_id": -1,
            "is_read": true,
            "type_int": 13,
            "push_title": "안내",
            "thumbnail": "https://storage.cobak.co/image/pushalert_cobak_profile2.jpg",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15904177,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"가상자산 특화 은행의 파산...\"",
            "timestamp": "1678926807",
            "post_id": 870356,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15903355,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"상장 뒷돈, 빗썸홀딩스 압수..\"",
            "timestamp": "1678883483",
            "post_id": 869792,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15899476,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"와. 비트가 드디어 작년 8..\"",
            "timestamp": "1678798880",
            "post_id": 868731,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15899129,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"으하하!. 이더 종가 맞추기..\"",
            "timestamp": "1678786261",
            "post_id": 868377,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15893651,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"혼자만 파랑이인 리플\"",
            "timestamp": "1678745750",
            "post_id": 867881,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15893273,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"국세청, 메디블록 세무조사 ..\"",
            "timestamp": "1678717041",
            "post_id": 867530,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15890511,
            "type": "NEW_HOT_POST",
            "text": "소타님이 새로운 글을 올렸습니다. \"ㅅㅈㅁ의 문단속 후기\"",
            "timestamp": "1678683752",
            "post_id": 867115,
            "is_read": true,
            "user": {
                "id": 476923,
                "uid": "00c0c6c4ca",
                "gender": "N",
                "level": 59,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": true,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2021-08-02T10:40:24.716179",
                "is_media": false,
                "last_ip": "52.78.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "소타",
                "photo": "https://storage.cobak.co/uploads/1678683501475132_dd673fbf56.jpeg",
                "thumbnail": "https://storage.cobak.co/uploads/1678683501475132_dd673fbf56_thumb.jpeg",
                "intro": "스즈메의 문단속",
                "web_page": "",
                "is_following": false,
                "is_influencer": false,
                "is_expert": false
            },
            "category": {
                "id": 7,
                "title": "자유게시판",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_08.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련되지 않은 주제의 게시글을 작성하는 게시판입니다.",
                "order_web": 8,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15889224,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"SVB 파산 여파. 암호화폐..\"",
            "timestamp": "1678628291",
            "post_id": 866635,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15887994,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"USDC, 테라 사태 때와는..\"",
            "timestamp": "1678587800",
            "post_id": 866518,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15887298,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"#종가맞추기 도잔합니다. 침..\"",
            "timestamp": "1678537963",
            "post_id": 866402,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15885363,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"실리콘밸리은행, -60% 폭..\"",
            "timestamp": "1678454202",
            "post_id": 865806,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15879748,
            "type": "NEW_HOT_POST",
            "text": "더글로리 문동은님이 새로운 글을 올렸습니다. \"금양그린퐈워!\"",
            "timestamp": "1678425458",
            "post_id": 865441,
            "is_read": true,
            "user": {
                "id": 476923,
                "uid": "00c0c6c4ca",
                "gender": "N",
                "level": 59,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": true,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2021-08-02T10:40:24.716179",
                "is_media": false,
                "last_ip": "52.78.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "소타",
                "photo": "https://storage.cobak.co/uploads/1678683501475132_dd673fbf56.jpeg",
                "thumbnail": "https://storage.cobak.co/uploads/1678683501475132_dd673fbf56_thumb.jpeg",
                "intro": "스즈메의 문단속",
                "web_page": "",
                "is_following": false,
                "is_influencer": false,
                "is_expert": false
            },
            "category": {
                "id": 7,
                "title": "자유게시판",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_08.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련되지 않은 주제의 게시글을 작성하는 게시판입니다.",
                "order_web": 8,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        },
        {
            "id": 15878621,
            "type": "NEW_HOT_POST",
            "text": "장콕토님이 새로운 글을 올렸습니다. \"대만. 인플루언서 광고에 공..\"",
            "timestamp": "1678402969",
            "post_id": 865157,
            "is_read": true,
            "user": {
                "id": 357388,
                "uid": "4e4eb4fb09",
                "gender": "N",
                "level": 74,
                "is_blocked": false,
                "is_official": false,
                "is_hide_balance": false,
                "coin_id": -1,
                "is_black_user": true,
                "date_joined": "2020-11-08T20:54:31.559537",
                "is_media": false,
                "last_ip": "218.50.***.***",
                "is_admin": false,
                "whale_level": 0,
                "nickname": "장콕토",
                "photo": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200.gif",
                "thumbnail": "https://storage.cobak.co/uploads/1669342356130226_fdf951b200_thumb.gif",
                "intro": "",
                "web_page": "",
                "is_following": false,
                "is_influencer": true,
                "is_expert": false,
                "official_image": "https://storage.cobak.co/custom_upload/badge_influencer.png"
            },
            "category": {
                "id": 1,
                "title": "코인잡담",
                "readable": true,
                "min_write_level": -1,
                "max_write_level": -1,
                "thumbnail": "https://storage.cobak.co/direct/commu_menu_icon_02.png",
                "type": "normal",
                "link": null,
                "coin_attach_force": false,
                "is_writable": true,
                "is_ad": false,
                "description": "코인 및 블록체인과 관련된 게시글을 자유롭게 작성하는 게시판입니다.",
                "order_web": 3,
                "recent_post_count": 0
            },
            "type_int": 6,
            "push_title": "새로운 글 업로드",
            "click": {
                "command": ""
            }
        }
    ],
    "status": 200
}"""